import { useEffect, useRef, useState, type FormEvent } from 'react';
import { apiFetch } from '../../radius/api';
import { sincronizarPaciente } from '../../radius/pacientesCompartidos';
import Icon from '../../radius/componentes/Icono';
import './TriajeEmergenciasView.css';
import { cubiculosEmergencias, nombreCubiculo } from './cubiculos';
import { OrdenesEmergencias } from './OrdenesEmergencias';
import { camposEvaluacion, nombrePaciente, type CuentaEmergencia } from './emergenciasApi';
import { HorizontalSubvistaNav } from '../../ui/components/HorizontalSubvistaNav';

type Item = { id: string; codigo: string; nombre: string; tipo: 'servicio' | 'producto'; unidad: string; precio: number };
type Consumo = Item & { registroId: string; cantidad: number; porHora: boolean; inicio: string; fin: string | null };
type Identidad = Record<string, string>;
type Cuenta = CuentaEmergencia;
const dinero = (n: number) => `Bs ${n.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fecha = (v: string) => new Date(v).toLocaleString('es-BO');
const duracion = (c: Consumo, ahora: number) => Math.max(0, (c.fin ? Date.parse(c.fin) : ahora) - Date.parse(c.inicio));
const importe = (c: Consumo, ahora: number) => Math.round(c.precio * (c.porHora ? duracion(c, ahora) / 3600000 : c.cantidad) * 100) / 100;
const reloj = (ms: number) => { const s = Math.floor(ms / 1000); return `${String(Math.floor(s / 3600)).padStart(2, '0')}:${String(Math.floor(s / 60) % 60).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`; };
const campos = [['temperatura', 'Temperatura', '°C'], ['frecuenciaCardiaca', 'Frec. cardíaca', 'lpm'], ['frecuenciaRespiratoria', 'Frec. respiratoria', 'rpm'], ['presionSistolica', 'Presión sistólica', 'mmHg'], ['presionDiastolica', 'Presión diastólica', 'mmHg'], ['saturacion', 'Saturación', '%'], ['glicemia', 'Glicemia', 'mg/dL'], ['peso', 'Peso', 'kg']];
const normalizar = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
async function pedir<T>(ruta = '', body?: object): Promise<T> {
  const respuesta = await apiFetch(`/api/emergencias${ruta}`, body ? { method: 'POST', body: JSON.stringify(body) } : {});
  const datos = await respuesta.json();
  if (!respuesta.ok) throw new Error(datos.message || 'No se pudo completar la operación.');
  return datos;
}

export function TriajeEmergenciasView({ recepcion = false }: { recepcion?: boolean }) {
  const [subvista, setSubvista] = useState<'atencion' | 'descargos'>('atencion');
  const [seccionClinica, setSeccionClinica] = useState<'ingreso' | 'signos' | 'examen'>('ingreso');
  const [seccionDescargos, setSeccionDescargos] = useState<'consumo' | 'evolucion'>('consumo');
  const [descargosAbiertos, setDescargosAbiertos] = useState(false);
  const mostrarAtencion = subvista === 'atencion';
  const [cuentas, setCuentas] = useState<Cuenta[]>([]), [activa, setActiva] = useState('');
  const [cargando, setCargando] = useState(true), [ocupado, setOcupado] = useState(false), [error, setError] = useState(''), [aviso, setAviso] = useState('');
  const [ahora, setAhora] = useState(Date.now()), desfase = useRef(0), ultimaLectura = useRef(0);
  const [cubiculo, setCubiculo] = useState(''), [nueva, setNueva] = useState(false), solicitud = useRef(crypto.randomUUID());
  const [selectorCubiculoAbierto, setSelectorCubiculoAbierto] = useState(false);
  const [errorCubiculo, setErrorCubiculo] = useState('');
  const [cubiculosPlegados, setCubiculosPlegados] = useState(false);
  const [datosIniciales, setDatosIniciales] = useState<Identidad>({});
  const [mostrarAcompanante, setMostrarAcompanante] = useState(false);
  const [busquedaCuenta, setBusquedaCuenta] = useState(''), [verFinalizadas, setVerFinalizadas] = useState(false);
  const [catalogo, setCatalogo] = useState<Item[]>([]), [errorCatalogo, setErrorCatalogo] = useState(''), [busqueda, setBusqueda] = useState('');
  const [itemId, setItemId] = useState(''), [cantidad, setCantidad] = useState('1'), [porHora, setPorHora] = useState(false);
  const [valores, setValores] = useState<Record<string, string>>({}), [observacion, setObservacion] = useState(''), [editarSignos, setEditarSignos] = useState(false);
  const [identidad, setIdentidad] = useState<Identidad | null>(null), [revisionIdentidad, setRevisionIdentidad] = useState(0);
  const datosPacienteRef = useRef<HTMLElement>(null);
  const operacionActiva = useRef(false), intentoConsumo = useRef<{ clave: string; id: string } | null>(null);
  const cuenta = cuentas.find(c => c.id === activa), item = catalogo.find(i => i.id === itemId);
  async function cargar() {
    if (operacionActiva.current) return;
    const lectura = ++ultimaLectura.current;
    try {
      const datos = await pedir<{ cuentas: Cuenta[]; ahora: string }>();
      if (lectura !== ultimaLectura.current) return;
      desfase.current = Date.parse(datos.ahora) - Date.now(); setAhora(Date.now() + desfase.current);
      setCuentas(datos.cuentas);
    } catch (e) { setError((e as Error).message); } finally { setCargando(false); }
  }
  async function cargarCatalogo() { try { setCatalogo(await pedir<Item[]>('/catalogo')); setErrorCatalogo(''); } catch (e) { setErrorCatalogo((e as Error).message); } }
  useEffect(() => { void cargar(); if (!recepcion) void cargarCatalogo(); const t = window.setInterval(() => void cargar(), 5000); const r = window.setInterval(() => setAhora(Date.now() + desfase.current), 1000); return () => { clearInterval(t); clearInterval(r); ultimaLectura.current++; }; }, [recepcion]);
  useEffect(() => { if (cubiculo) setErrorCubiculo(''); }, [cubiculo]);
  function seleccionar(id: string) { setActiva(id); setSeccionClinica('ingreso'); setIdentidad(null); setEditarSignos(false); setValores({}); setObservacion(''); setItemId(''); setAviso(''); setError(''); }
  async function guardar(ruta: string, body: object, mensaje: string) {
    if (operacionActiva.current) return false;
    operacionActiva.current = true;
    if (ruta.endsWith('/consumos')) {
      const datos = body as Record<string, unknown>;
      const clave = JSON.stringify([ruta, datos.itemId, datos.precio, datos.cantidad, datos.porHora]);
      if (intentoConsumo.current?.clave !== clave) intentoConsumo.current = { clave, id: String(datos.registroId) };
      body = { ...datos, registroId: intentoConsumo.current.id };
    }
    setOcupado(true); setError(''); setAviso(''); ++ultimaLectura.current;
    try {
      const actualizada = await pedir<Cuenta>(ruta, body); ++ultimaLectura.current;
      intentoConsumo.current = null;
      setCuentas(prev => [actualizada, ...prev.filter(c => c.id !== actualizada.id)]); setActiva(actualizada.id); setAviso(mensaje); if (ruta.endsWith('/identidad')) void sincronizarFicha(body as Identidad); return true;
    } catch (e) { setError((e as Error).message); return false; } finally { operacionActiva.current = false; setOcupado(false); }
  }
  async function sincronizarFicha(datos: Identidad) {
    if (!datos.nombres?.trim() || !datos.documento?.trim()) return;
    try { await sincronizarPaciente(datos); }
    catch (e) { setError(`La atención fue guardada, pero no se pudo sincronizar la ficha general: ${(e as Error).message}`); }
  }
  async function iniciar(e: FormEvent) { e.preventDefault(); if (!cubiculo) { setErrorCubiculo('Debes seleccionar un cubículo de atención antes de registrar al paciente.'); setSelectorCubiculoAbierto(true); requestAnimationFrame(() => document.querySelector<HTMLButtonElement>('.em-selector-cubiculo > button')?.focus()); return; } setErrorCubiculo(''); if (await guardar('', { cubiculo, identidad: datosIniciales, solicitudId: solicitud.current }, 'Atención iniciada. La cuenta ya está disponible en Recepción.')) { await sincronizarFicha(datosIniciales); solicitud.current = crypto.randomUUID(); setNueva(false); setCubiculo(''); setSelectorCubiculoAbierto(false); setDatosIniciales({}); setMostrarAcompanante(false); setIdentidad(null); setValores({}); setObservacion(''); } }
  async function registrarSignos(e: FormEvent) { e.preventDefault(); if (!cuenta) return; if (await guardar(`/${cuenta.id}/signos`, { valores: Object.fromEntries(Object.entries(valores).filter(([, v]) => v !== '').map(([k, v]) => [k, Number(v)])), observacion }, 'Signos vitales guardados.')) { setEditarSignos(false); setValores({}); setObservacion(''); } }
  function abrirDatosPaciente() { if (!cuenta) return; setIdentidad(cuenta.identidad || {}); setRevisionIdentidad(cuenta.revision); window.setTimeout(() => datosPacienteRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); }
  const visibles = cuentas.filter(c => (recepcion || verFinalizadas || !c.fin) && normalizar(`${c.cubiculo} ${c.identidad?.nombres || ''} ${c.identidad?.apellidos || ''} ${c.identidad?.documento || ''}`).includes(normalizar(busquedaCuenta)));
  const total = cuenta?.consumos.reduce((s, c) => s + importe(c, ahora), 0) || 0;
  const mostrarListadoDescargos = !recepcion && !mostrarAtencion && !descargosAbiertos;
  return <section className={`emergencias-vista ${cubiculosPlegados ? 'cubiculos-plegados' : ''}`}>
    {!recepcion && <HorizontalSubvistaNav className="em-subvistas" ariaLabel="Subvistas de Triaje de emergencias">
      <button type="button" className={mostrarAtencion ? 'activo' : ''} aria-current={mostrarAtencion ? 'page' : undefined} onClick={() => setSubvista('atencion')}><Icon name="patient" size={18} /><strong>Atención paciente</strong></button>
      <button type="button" className={!mostrarAtencion ? 'activo' : ''} aria-current={!mostrarAtencion ? 'page' : undefined} onClick={() => { setSubvista('descargos'); setDescargosAbiertos(false); }}><Icon name="fileText" size={18} /><strong>Descargos y aplicaciones</strong></button>
    </HorizontalSubvistaNav>}
    {!recepcion && <button type="button" className="em-toggle-cubiculos" aria-expanded={!cubiculosPlegados} onClick={() => setCubiculosPlegados(actual => !actual)}><Icon name={cubiculosPlegados ? 'chevronRight' : 'chevronLeft'} size={16} />{cubiculosPlegados ? 'Mostrar cubículos' : 'Ocultar cubículos'}</button>}
    {(recepcion || !mostrarAtencion) && <header className="em-cabecera"><div>{recepcion && <p>RECEPCIÓN · CUENTAS</p>}<h2>{recepcion ? 'Cuentas de emergencias' : 'Descargos y aplicaciones'}</h2>{recepcion && <small>Identifica al paciente y a su acompañante sin interrumpir la atención.</small>}</div></header>}
    {error && <div className="em-error" role="alert">{error} <button onClick={() => void cargar()}>Actualizar cuentas</button></div>}
    {aviso && <div className="em-aviso" role="status">{aviso}</div>}
    {nueva && !recepcion && <form className="em-panel em-inicio-atencion" hidden={!mostrarAtencion} onSubmit={iniciar}>
      <div className="em-inicio-cabecera"><div><h3>Iniciar atención de emergencias</h3><small>El cubículo es obligatorio. Puedes registrar los datos que conozcas o iniciar sin identificar al paciente.</small></div><div className="em-selector-cubiculo" onKeyDown={e => { if (e.key === 'Escape') setSelectorCubiculoAbierto(false); }}><span>Cubículo de atención *</span><button type="button" disabled={ocupado} className={cubiculo ? 'seleccionado' : ''} aria-haspopup="listbox" aria-expanded={selectorCubiculoAbierto} onClick={() => setSelectorCubiculoAbierto(abierto => !abierto)}>{cubiculo ? nombreCubiculo(cubiculo) : 'Selecciona un cubículo'}<Icon name="chevronDown" size={16} /></button>{selectorCubiculoAbierto && <div className="em-opciones-cubiculo" role="listbox" aria-label="Cubículo de atención">{cubiculosEmergencias.map(c => <button type="button" role="option" aria-selected={cubiculo === c.id} key={c.id} onClick={() => { setCubiculo(c.id); setSelectorCubiculoAbierto(false); solicitud.current = crypto.randomUUID(); }}>{cubiculo === c.id && <Icon name="check" size={15} />}{c.nombre}</button>)}</div>}</div></div>
      {errorCubiculo && <p className="em-error em-error-cubiculo" role="alert">{errorCubiculo}</p>}
      <fieldset className="em-datos-iniciales" disabled={ocupado}><legend>Datos básicos del paciente · opcionales</legend><div className="em-form-grid">{[['nombres', 'Nombres'], ['apellidos', 'Apellidos'], ['documento', 'Documento de identidad'], ['nacimiento', 'Fecha de nacimiento'], ['telefono', 'Teléfono']].map(([k, titulo]) => <label key={k}>{titulo}<input type={k === 'nacimiento' ? 'date' : k === 'telefono' ? 'tel' : 'text'} maxLength={200} value={datosIniciales[k] || ''} onChange={e => { setDatosIniciales(actual => ({ ...actual, [k]: e.target.value })); solicitud.current = crypto.randomUUID(); }} /></label>)}</div></fieldset>
      <div className="em-acompanante-toggle"><button type="button" disabled={ocupado} aria-expanded={mostrarAcompanante} aria-controls="em-datos-acompanante" onClick={() => setMostrarAcompanante(abierto => !abierto)}><Icon name={mostrarAcompanante ? 'chevronDown' : 'plus'} size={16} />{mostrarAcompanante ? 'Ocultar datos del acompañante/responsable' : 'Registrar acompañante/responsable'}</button></div>
      <fieldset id="em-datos-acompanante" className="em-datos-iniciales" hidden={!mostrarAcompanante} disabled={ocupado}>
        <legend>Datos del acompañante / responsable · opcionales</legend>
        <div className="em-form-grid">{[['familiar', 'Nombre completo'], ['parentesco', 'Parentesco o relación'], ['documentoFamiliar', 'Documento de identidad'], ['telefonoFamiliar', 'Teléfono']].map(([k, titulo]) => <label key={k}>{titulo}<input type={k === 'telefonoFamiliar' ? 'tel' : 'text'} maxLength={200} value={datosIniciales[k] || ''} onChange={e => { setDatosIniciales(actual => ({ ...actual, [k]: e.target.value })); solicitud.current = crypto.randomUUID(); }} /></label>)}</div>
      </fieldset>
      <div className="em-acciones"><button className="em-primario" type="submit" disabled={ocupado}>Registrar paciente</button></div>
    </form>}
    <div className={`em-distribucion ${nueva && !recepcion ? 'formulario-abierto' : ''} ${!recepcion && !mostrarAtencion ? 'sin-columna-lateral' : ''}`}><aside className="em-panel em-cubiculos" hidden={!recepcion && !mostrarAtencion}><label className="em-buscar"><Icon name="search" size={16} /><input aria-label="Buscar cuenta" placeholder="Cubículo, paciente o documento" value={busquedaCuenta} onChange={e => setBusquedaCuenta(e.target.value)} /></label>{!recepcion && <label className="em-check"><input type="checkbox" checked={verFinalizadas} onChange={e => setVerFinalizadas(e.target.checked)} /> Incluir finalizadas</label>}<small>{cuentas.filter(c => !c.fin).length} atenciones activas</small>{visibles.map(c => <button key={c.id} className={`em-cubiculo ${activa === c.id ? 'seleccionado' : ''}`} onClick={() => { seleccionar(c.id); if (!recepcion && !mostrarAtencion) setDescargosAbiertos(true); }}><strong>{nombreCubiculo(c.cubiculo)}</strong><span>{nombrePaciente(c)}</span><small>{c.fin ? 'Atención finalizada' : c.signos.length ? 'En atención' : 'Signos vitales pendientes'} · {new Date(c.inicio).toLocaleTimeString('es-BO', { hour: '2-digit', minute: '2-digit' })}</small><b>{dinero(c.consumos.reduce((s, i) => s + importe(i, ahora), 0))}</b></button>)}{!visibles.length && <p className="em-vacio">{cargando ? 'Cargando cuentas…' : 'No hay cuentas para mostrar.'}</p>}</aside>
    <main className="em-trabajo">{mostrarListadoDescargos ? <section className="em-panel em-listado-descargos"><header><div><p>PACIENTES EN CUBÍCULO</p><h3>Atenciones activas</h3><small>Selecciona un paciente para registrar sus consumos y aplicaciones.</small></div><b>{visibles.filter(c => !c.fin).length} activos</b></header><div className="em-listado-descargos-tabla"><div className="em-listado-descargos-encabezado"><span>Cubículo de atención</span><span>Nombre y apellido</span><span>CI</span><span>Diagnóstico de ingreso</span><span>Opciones</span></div>{visibles.filter(c => !c.fin).map(c => <article key={c.id}><div><strong>{nombreCubiculo(c.cubiculo)}</strong><small>Ingreso {new Date(c.inicio).toLocaleTimeString('es-BO', { hour: '2-digit', minute: '2-digit' })}</small></div><div><strong>{nombrePaciente(c)}</strong></div><div><span>{c.identidad?.documento || 'No registrado'}</span></div><div><span>{c.evaluaciones?.at(-1)?.campos.diagnostico || 'Sin diagnóstico registrado'}</span></div><button className="em-primario" type="button" onClick={() => { seleccionar(c.id); setDescargosAbiertos(true); }}><Icon name="edit" size={16} /> Atender / registrar</button></article>)}{!visibles.filter(c => !c.fin).length && <p className="em-vacio">No hay pacientes ocupando cubículos.</p>}</div></section> : !cuenta ? <div className="em-panel em-vacio"><Icon name="patient" size={32} /><h3>{recepcion ? 'Selecciona una cuenta' : mostrarAtencion ? 'Listo para recibir al paciente' : 'Selecciona un paciente'}</h3><p>{recepcion ? 'Las cuentas creadas en triaje aparecerán aquí.' : mostrarAtencion ? 'Inicia una atención con el número de cubículo, sin necesidad de datos personales.' : 'Elige un cubículo de la lista para revisar las indicaciones y registrar sus aplicaciones y consumos.'}</p>{!recepcion && mostrarAtencion && <button className="em-primario em-iniciar-vacio" onClick={() => setNueva(true)}><Icon name="plus" size={16} /> Iniciar atención</button>}</div> : <>
      <div className="em-panel em-resumen"><div className="em-resumen-datos"><div className="em-resumen-fila em-resumen-fila-uno"><div><span>Código de cuenta</span><strong className="em-resumen-cuenta">{cuenta.id.slice(0, 8).toUpperCase()}</strong></div><div className="em-resumen-cubiculo"><span>Cubículo de atención</span><strong>{nombreCubiculo(cuenta.cubiculo)}</strong></div><div><span>Fecha y hora de ingreso</span><strong>{fecha(cuenta.inicio)}{cuenta.fin ? ' · Atención finalizada' : ''}</strong></div></div><div className="em-resumen-fila em-resumen-fila-dos"><div><span>Paciente</span><strong>{cuenta.identidad?.nombres || cuenta.identidad?.apellidos ? nombrePaciente(cuenta) : 'Sin registro'}</strong></div><div><span>N.º de historia clínica</span><strong>Sin registro</strong></div><div><span>Familiar / responsable</span><strong>{cuenta.identidad?.familiar || 'Sin registro'}</strong></div></div><div className="em-resumen-fila em-resumen-fila-tres"><div><span>Profesional tratante</span><strong>Sin registro</strong></div><div><span>Diagnóstico de ingreso</span><strong>{cuenta.evaluaciones?.at(-1)?.campos.diagnostico || 'Sin registro'}</strong></div></div></div><div className="em-total"><small>Total consumido</small><strong>{dinero(total)}</strong><small>{cuenta.consumos.some(c => c.porHora && !c.fin) ? 'Incluye servicios en curso' : 'Registrado en la cuenta'}</small>{recepcion && !cuenta.identidad && <button className="em-completar-paciente" type="button" onClick={abrirDatosPaciente}><Icon name="edit" size={15} /> Completar datos</button>}</div></div>
      {!recepcion && !mostrarAtencion && <HorizontalSubvistaNav className="em-subvistas em-descargos-nav" ariaLabel="Apartados de descargos y aplicaciones">
        <button type="button" className={seccionDescargos === 'consumo' ? 'activo' : ''} aria-current={seccionDescargos === 'consumo' ? 'page' : undefined} onClick={() => setSeccionDescargos('consumo')}><Icon name="fileText" size={17} /><strong>Consumo</strong></button>
        <button type="button" className={seccionDescargos === 'evolucion' ? 'activo' : ''} aria-current={seccionDescargos === 'evolucion' ? 'page' : undefined} onClick={() => setSeccionDescargos('evolucion')}><Icon name="edit" size={17} /><strong>Evolución</strong></button>
      </HorizontalSubvistaNav>}
      {!recepcion && <>
        {!!cuenta.evaluaciones?.length && <section className="em-panel" hidden={!mostrarAtencion}><header className="em-panel-titulo"><h3>Información y evaluación médica</h3><small>Última actualización: {fecha(cuenta.evaluaciones.at(-1)!.fecha)}</small></header><details><summary>Ver notas del médico</summary>{camposEvaluacion.filter(([k]) => cuenta.evaluaciones!.at(-1)!.campos[k]).map(([k, t]) => <p className="em-texto-clinico" key={k}><strong>{t}: </strong>{cuenta.evaluaciones!.at(-1)!.campos[k]}</p>)}</details></section>}
        <div className="em-descargos-indicaciones" hidden={mostrarAtencion || seccionDescargos !== 'consumo'}>
          {!cuenta.signos.length && <p className="em-pendiente">Registra primero los signos vitales en «Atención paciente» para poder aplicar indicaciones.</p>}
          <OrdenesEmergencias key={cuenta.id} cuenta={cuenta} catalogo={catalogo} guardar={guardar} ocupado={ocupado} enfermeria />
        </div>
      </>}
      {recepcion && <section ref={datosPacienteRef} className={`em-panel em-identidad-panel ${!cuenta.identidad ? 'pendiente' : ''}`}><header className="em-panel-titulo"><div className="em-identidad-titulo"><span><Icon name="patient" size={18} /></span><div><small>IDENTIFICACIÓN DE LA CUENTA</small><h3>Datos del paciente y acompañante</h3></div></div>{!identidad && <button className="em-identidad-boton" onClick={abrirDatosPaciente}><Icon name="edit" size={15} /> {cuenta.identidad ? 'Editar datos' : 'Completar datos'}</button>}</header>{identidad && <form onSubmit={async e => { e.preventDefault(); if (await guardar(`/${cuenta.id}/identidad`, { ...identidad, revision: revisionIdentidad }, 'Datos guardados en la cuenta.')) setIdentidad(null); }}><div className="em-form-grid">{[['nombres', 'Nombres'], ['apellidos', 'Apellidos'], ['documento', 'Documento de identidad'], ['nacimiento', 'Fecha de nacimiento'], ['telefono', 'Teléfono del paciente'], ['direccion', 'Dirección'], ['familiar', 'Nombre del familiar / acompañante'], ['parentesco', 'Parentesco'], ['telefonoFamiliar', 'Teléfono del acompañante'], ['documentoFamiliar', 'Documento del acompañante']].map(([k, titulo]) => <label key={k}>{titulo}<input type={k === 'nacimiento' ? 'date' : 'text'} maxLength={200} value={identidad[k] || ''} onChange={e => setIdentidad({ ...identidad, [k]: e.target.value })} /></label>)}</div><div className="em-acciones"><button type="button" onClick={() => setIdentidad(null)}>Cancelar</button><button className="em-primario" disabled={ocupado}>Guardar datos</button></div></form>}{!identidad && (cuenta.identidad ? <div className="em-identidad-registrada"><Icon name="check" size={17} /><p><strong>Identificación registrada</strong><span>Documento: {cuenta.identidad.documento || 'No registrado'} · Familiar: {cuenta.identidad.familiar || 'No registrado'}</span></p></div> : <div className="em-identidad-vacia"><span><Icon name="patient" size={22} /></span><p><strong>Paciente pendiente de identificar</strong><small>Completa sus datos cuando estén disponibles. La cuenta y todos sus consumos se conservarán.</small></p></div>)}</section>}
      {!recepcion && <section className="em-atencion-clinica" hidden={!mostrarAtencion}>
        <nav className="em-paginacion-clinica" aria-label="Registro de atención de emergencia">
          <button type="button" className={seccionClinica === 'ingreso' ? 'activo' : ''} aria-current={seccionClinica === 'ingreso' ? 'page' : undefined} onClick={() => setSeccionClinica('ingreso')}><span>1</span>Registro de ingreso</button>
          <button type="button" className={seccionClinica === 'signos' ? 'activo' : ''} aria-current={seccionClinica === 'signos' ? 'page' : undefined} onClick={() => setSeccionClinica('signos')}><span>2</span>Signos vitales</button>
          <button type="button" className={seccionClinica === 'examen' ? 'activo' : ''} aria-current={seccionClinica === 'examen' ? 'page' : undefined} onClick={() => setSeccionClinica('examen')}><span>3</span>Examen físico regional</button>
        </nav>
        {seccionClinica === 'ingreso' && <section className="em-panel em-registro-ingreso"><header className="em-panel-titulo"><div><h3>Registro de ingreso</h3><small>Información disponible al momento de recibir al paciente.</small></div></header><div><div><span>Motivo de atención</span><strong>{cuenta.evaluaciones?.at(-1)?.campos.motivoConsulta || 'Sin registro'}</strong></div><div><span>Diagnóstico de ingreso</span><strong>{cuenta.evaluaciones?.at(-1)?.campos.diagnostico || 'Sin registro'}</strong></div><div><span>Historia clínica</span><strong>Sin registro</strong></div></div></section>}
        {seccionClinica === 'signos' && <section className="em-panel"><header className="em-panel-titulo"><h3>Signos vitales</h3>{!!cuenta.signos.length && !cuenta.fin && <button onClick={() => setEditarSignos(!editarSignos)}>Nueva medición</button>}</header>{(!cuenta.signos.length || editarSignos) && !cuenta.fin ? <form onSubmit={registrarSignos}><div className="em-form-grid em-signos">{campos.map(([k, titulo, unidad]) => <label key={k}>{titulo}<span><input type="number" min="0" max={k === 'saturacion' ? 100 : undefined} step="any" value={valores[k] || ''} onChange={e => setValores({ ...valores, [k]: e.target.value })} />{unidad}</span></label>)}</div><label>Observación o motivo de medición no disponible<textarea value={observacion} maxLength={1000} onChange={e => setObservacion(e.target.value)} /></label><div className="em-acciones"><button className="em-primario" disabled={ocupado}>Guardar signos vitales</button></div></form> : <div className="em-mediciones">{[...cuenta.signos].reverse().map(s => <details key={s.id}><summary>{fecha(s.fecha)} · {Object.entries(s.valores).map(([k, v]) => `${campos.find(c => c[0] === k)?.[1]}: ${v}`).join(' · ') || 'Medición no disponible'}</summary><p>{s.observacion || 'Sin observaciones adicionales.'}</p></details>)}</div>}</section>}
        {seccionClinica === 'examen' && <section className="em-panel em-examen-regional"><header className="em-panel-titulo"><div><h3>Examen físico regional</h3><small>Registro clínico por regiones anatómicas.</small></div></header><div className="em-vacio"><Icon name="patient" size={28} /><p>El examen físico regional se habilitará en este apartado.</p></div></section>}
      </section>}
      {!recepcion && !mostrarAtencion && seccionDescargos === 'evolucion' && <section className="em-panel em-descargos-evolucion"><header className="em-panel-titulo"><div><h3>Evolución del paciente</h3><small>Seguimiento clínico registrado durante la atención.</small></div></header>{cuenta.evaluaciones?.length ? <div className="em-evolucion-lista">{[...cuenta.evaluaciones].reverse().map(evaluacion => <article key={evaluacion.id}><time>{fecha(evaluacion.fecha)}</time>{camposEvaluacion.filter(([campo]) => evaluacion.campos[campo]).map(([campo, titulo]) => <p key={campo}><strong>{titulo}</strong><span>{evaluacion.campos[campo]}</span></p>)}</article>)}</div> : <p className="em-vacio">Aún no hay registros de evolución para este paciente.</p>}</section>}
      <div className="em-descargos-consumo" hidden={!recepcion && (mostrarAtencion || seccionDescargos !== 'consumo')}>
      {!recepcion && !cuenta.fin && <section className="em-panel" hidden={mostrarAtencion}><header className="em-panel-titulo"><h3>Registrar consumo</h3><small>Catálogo de Contabilidad</small></header>{!cuenta.signos.length && <p className="em-pendiente">Guarda la valoración inicial para registrar consumos.</p>}{errorCatalogo && <p className="em-error">{errorCatalogo}</p>}<div className="em-buscador-catalogo"><label className="em-buscar"><Icon name="search" size={16} /><input placeholder="Buscar servicio, producto o insumo…" aria-label="Buscar consumo" value={busqueda} onChange={e => { setBusqueda(e.target.value); setItemId(''); }} /></label><button onClick={() => void cargarCatalogo()}>Actualizar catálogo</button></div>{!catalogo.length && !errorCatalogo && <p>No hay ítems activos con precio aprobado. Regístralos en el catálogo de Contabilidad.</p>}{busqueda && !item && <div className="em-resultados">{catalogo.filter(i => normalizar(`${i.nombre} ${i.codigo}`).includes(normalizar(busqueda))).slice(0, 30).map(i => <button key={i.id} onClick={() => { setItemId(i.id); setPorHora(i.tipo === 'servicio' && ['TIEMPO', 'HORA', 'HORAS'].includes(i.unidad.toUpperCase())); setCantidad('1'); }}><span><strong>{i.nombre}</strong><small>{i.codigo} · {i.tipo === 'servicio' ? 'Servicio' : 'Producto / insumo'} · {i.unidad}</small></span><b>{dinero(i.precio)}</b></button>)}{!catalogo.some(i => normalizar(`${i.nombre} ${i.codigo}`).includes(normalizar(busqueda))) && <p>Sin coincidencias.</p>}</div>}{item && <form className="em-agregar" onSubmit={async e => { e.preventDefault(); if (await guardar(`/${cuenta.id}/consumos`, { itemId: item.id, precio: item.precio, cantidad: Number(cantidad), porHora, registroId: crypto.randomUUID() }, porHora ? 'Servicio iniciado. El contador seguirá activo hasta finalizar su uso.' : 'Consumo registrado.')) { setItemId(''); setBusqueda(''); } }}><strong>{item.nombre}</strong>{item.tipo === 'servicio' && <label>Modalidad<select value={porHora ? 'hora' : 'unidad'} onChange={e => setPorHora(e.target.value === 'hora')}><option value="unidad">Por aplicación / unidad</option><option value="hora">Por hora · proporcional</option></select></label>}{!porHora && <label>Cantidad<input required type="number" min="0.001" max="100000" step="any" value={cantidad} onChange={e => setCantidad(e.target.value)} /></label>}<span>{dinero(item.precio)} / {porHora ? 'hora' : item.unidad}</span><button className="em-primario" disabled={ocupado || !cuenta.signos.length}>{porHora ? 'Iniciar servicio' : 'Agregar consumo'}</button>{porHora && <small>Confirma que esta tarifa corresponde a una hora. Se cobrará la fracción exacta de tiempo utilizado.</small>}</form>}</section>}
      <section className="em-panel em-tabla-consumos"><header className="em-panel-titulo"><div><h3>Consumos registrados</h3><small>Servicios, productos e insumos cargados a la cuenta del paciente.</small></div><b>{dinero(total)}</b></header>{cuenta.consumos.length ? <div className="em-tabla-scroll"><table><thead><tr><th>Fecha y hora</th><th>Tipo</th><th>Detalle</th><th>Cantidad / modalidad</th><th>Estado</th><th>Importe</th><th>Acción</th></tr></thead><tbody>{[...cuenta.consumos].reverse().map(c => <tr key={c.registroId}><td>{fecha(c.inicio)}</td><td><span className="em-tipo-consumo">{c.tipo === 'servicio' ? 'Servicio' : 'Producto / insumo'}</span></td><td><strong>{c.nombre}</strong><small>{c.codigo} · {c.unidad}</small></td><td>{c.porHora ? `${dinero(c.precio)} / hora` : `${c.cantidad} × ${dinero(c.precio)}`}</td><td>{c.porHora ? <span className={`em-reloj ${!c.fin ? 'en-curso' : ''}`}>{!c.fin ? '● En curso' : 'Finalizado'} · {reloj(duracion(c, ahora))}</span> : 'Registrado'}</td><td><strong>{dinero(importe(c, ahora))}</strong></td><td>{c.porHora && !c.fin && !recepcion ? <button disabled={ocupado} onClick={() => void guardar(`/${cuenta.id}/finalizar-consumo`, { registroId: c.registroId }, 'Servicio finalizado. Importe fijado en la cuenta.')}>Finalizar uso</button> : '—'}</td></tr>)}</tbody></table></div> : <p className="em-vacio">Aún no hay consumos registrados.</p>}</section>
      </div>
      {!recepcion && !cuenta.fin && <div className="em-cierre" hidden={!mostrarAtencion}><small>Al finalizar, la cuenta se conserva en Recepción y el cubículo queda libre.</small><button disabled={ocupado || !cuenta.signos.length || cuenta.consumos.some(c => c.porHora && !c.fin)} onClick={() => { if (window.confirm('¿Finalizar esta atención y liberar el cubículo? La cuenta se conservará en Recepción.')) void guardar(`/${cuenta.id}/finalizar`, {}, 'Atención finalizada; cubículo disponible.'); }}>Finalizar atención</button></div>}
    </>}</main></div>
  </section>;
}
