import { useEffect, useMemo, useState, type FormEvent } from 'react';
import Icon from '../../componentes/Icono';
import { apiFetch } from '../../api';
import './VistaUsuarios.css';

type Usuario = { id: string; nombre: string; apellido: string; email: string; usuario?: string; ci?: string; telefono?: string; rolId: string; estado: string; creadoEn?: string };
const formularioInicial = { nombre: '', apellido: '', telefono: '', email: '', ci: '', password: '', confirmarPassword: '' };

export default function VistaUsuarios() {
  const [usuarios, setUsuarios] = useState<Usuario[]>([]);
  const [busqueda, setBusqueda] = useState('');
  const [estado, setEstado] = useState('todos');
  const [rol, setRol] = useState('todos');
  const [pagina, setPagina] = useState(1);
  const [porPagina, setPorPagina] = useState(10);
  const [cargando, setCargando] = useState(true);
  const [crearAbierto, setCrearAbierto] = useState(false);
  const [formulario, setFormulario] = useState(formularioInicial);
  const [errorFormulario, setErrorFormulario] = useState('');
  const [guardando, setGuardando] = useState(false);
  const [viendoUsuario, setViendoUsuario] = useState<Usuario | null>(null);
  const [editandoUsuario, setEditandoUsuario] = useState<Usuario | null>(null);
  const [edicion, setEdicion] = useState({ nombre: '', apellido: '', telefono: '', email: '', ci: '', estado: 'activo' });

  useEffect(() => { apiFetch('/api/usuarios').then(async (r) => r.ok ? r.json() : []).then(setUsuarios).catch(() => setUsuarios([])).finally(() => setCargando(false)); }, []);
  const roles = [...new Set(usuarios.map((u) => u.rolId).filter(Boolean))];
  const filtrados = useMemo(() => usuarios.filter((u) => {
    const texto = `${u.nombre} ${u.apellido} ${u.email} ${u.usuario || ''} ${u.ci || ''}`.toLowerCase();
    return texto.includes(busqueda.toLowerCase()) && (estado === 'todos' || u.estado === estado) && (rol === 'todos' || u.rolId === rol);
  }), [usuarios, busqueda, estado, rol]);
  const totalPaginas = Math.max(1, Math.ceil(filtrados.length / porPagina));
  const paginaActual = Math.min(pagina, totalPaginas);
  const visibles = filtrados.slice((paginaActual - 1) * porPagina, paginaActual * porPagina);
  const cambiarFiltro = (accion: () => void) => { accion(); setPagina(1); };
  const nombreRol = (id: string) => id === 'rol-administrador' ? 'Administrador' : id.replace(/^rol-/, '').replace(/-/g, ' ');
  const abrirEdicion = (u: Usuario) => { setEditandoUsuario(u); setEdicion({ nombre: u.nombre, apellido: u.apellido, telefono: u.telefono || '', email: u.email, ci: u.ci || '', estado: u.estado }); setErrorFormulario(''); };
  const guardarEdicion = async (evento: FormEvent) => { evento.preventDefault(); if (!editandoUsuario) return; setGuardando(true); setErrorFormulario(''); try { const respuesta = await apiFetch(`/api/usuarios/${editandoUsuario.id}`, { method: 'PUT', body: JSON.stringify(edicion) }); const datos = await respuesta.json(); if (!respuesta.ok) throw new Error(datos.message || 'No se pudo actualizar.'); setUsuarios((actuales) => actuales.map((u) => u.id === datos.id ? datos : u)); setEditandoUsuario(null); } catch (error) { setErrorFormulario(error instanceof Error ? error.message : 'No se pudo actualizar.'); } finally { setGuardando(false); } };
  const cerrarFormulario = () => { if (guardando) return; setCrearAbierto(false); setFormulario(formularioInicial); setErrorFormulario(''); };
  const guardarUsuario = async (evento: FormEvent) => {
    evento.preventDefault(); setErrorFormulario('');
    if (formulario.password !== formulario.confirmarPassword) return setErrorFormulario('Las contraseñas no coinciden.');
    if (formulario.password.length < 4) return setErrorFormulario('La contraseña debe tener al menos 4 caracteres.');
    setGuardando(true);
    try {
      const usuarioInterno = formulario.email.split('@')[0].toLowerCase().replace(/[^a-z0-9._-]/g, '');
      const respuesta = await apiFetch('/api/usuarios', { method: 'POST', body: JSON.stringify({ nombre: formulario.nombre, apellido: formulario.apellido, telefono: formulario.telefono, email: formulario.email, usuario: usuarioInterno, ci: formulario.ci, password: formulario.password, rolId: 'rol-administrador', estado: 'activo' }) });
      const datos = await respuesta.json();
      if (!respuesta.ok) throw new Error(datos.message || 'No se pudo crear el usuario.');
      setUsuarios((actuales) => [datos, ...actuales]); cerrarFormulario();
    } catch (error) { setErrorFormulario(error instanceof Error ? error.message : 'No se pudo crear el usuario.'); }
    finally { setGuardando(false); }
  };

  const Paginacion = ({ mostrarTamano = false }: { mostrarTamano?: boolean }) => <div className="usuarios-paginacion"><small>{filtrados.length ? `${(paginaActual - 1) * porPagina + 1}–${Math.min(paginaActual * porPagina, filtrados.length)} de ${filtrados.length}` : '0 resultados'}</small><div>{mostrarTamano && <label className="selector-tamano"><span>Tamaño</span><select value={porPagina} onChange={(e) => { setPorPagina(Number(e.target.value)); setPagina(1); }}>{[5, 10, 15, 20, 30, 50].map((cantidad) => <option key={cantidad} value={cantidad}>{cantidad}</option>)}</select></label>}<button disabled={paginaActual === 1} onClick={() => setPagina((p) => p - 1)} aria-label="Página anterior"><Icon name="chevronLeft" size={16} /></button><span>Página <strong>{paginaActual}</strong> de {totalPaginas}</span><button disabled={paginaActual === totalPaginas} onClick={() => setPagina((p) => p + 1)} aria-label="Página siguiente"><Icon name="chevronRight" size={16} /></button></div></div>;

  return <div className="usuarios-vista">
    <div className="usuarios-cabecera"><div><p>ADMINISTRACIÓN / USUARIOS</p><h2>Gestión de usuarios</h2><small>Administra las cuentas, roles y accesos del sistema.</small></div><button className="usuarios-crear" onClick={() => setCrearAbierto(true)}><Icon name="plus" size={18} /> Nuevo usuario</button></div>
    <div className="usuarios-herramientas"><label><Icon name="search" size={18} /><input value={busqueda} onChange={(e) => cambiarFiltro(() => setBusqueda(e.target.value))} placeholder="Buscar por nombre, usuario, correo o CI..." /></label><select value={rol} onChange={(e) => cambiarFiltro(() => setRol(e.target.value))}><option value="todos">Todos los roles</option>{roles.map((r) => <option value={r} key={r}>{nombreRol(r)}</option>)}</select><select value={estado} onChange={(e) => cambiarFiltro(() => setEstado(e.target.value))}><option value="todos">Todos los estados</option><option value="activo">Activos</option><option value="inactivo">Inactivos</option></select></div>
    <Paginacion mostrarTamano />
    <div className="usuarios-tabla"><div className="usuarios-fila usuarios-columnas"><span>Usuario</span><span>Contacto</span><span>Identificación y acceso</span><span>Rol</span><span>Estado</span><span>Registro</span><span /> </div>
      {cargando ? <div className="usuarios-mensaje">Cargando usuarios…</div> : visibles.length ? visibles.map((u) => <div className="usuarios-fila" key={u.id}><div className="usuario-identidad"><span><Icon name="users" size={19} /></span><div><strong>{u.nombre} {u.apellido}</strong><small>@{u.usuario || 'sin-usuario'}</small></div></div><div className="usuario-datos"><strong className="dato-movil">Contacto</strong><span>{u.email}</span><small>{u.telefono && u.telefono !== '—' ? u.telefono : 'Sin celular registrado'}</small></div><div className="usuario-datos"><strong className="dato-movil">Identificación y acceso</strong><span>CI: {u.ci || 'Sin registrar'}</span><small>Acceso con correo o CI</small></div><div><strong className="dato-movil">Rol</strong><span className="rol-etiqueta">{nombreRol(u.rolId)}</span></div><div><strong className="dato-movil">Estado</strong><span className={`estado-etiqueta ${u.estado}`}><i />{u.estado === 'activo' ? 'Activo' : 'Inactivo'}</span></div><div><strong className="dato-movil">Registro</strong><span>{u.creadoEn ? new Date(u.creadoEn).toLocaleDateString('es-ES') : '—'}</span></div><div className="acciones-tabla"><button className="usuario-accion" onClick={() => setViendoUsuario(u)} aria-label={`Ver a ${u.nombre}`} title="Ver información"><Icon name="eye" size={18} /></button><button className="usuario-accion" onClick={() => abrirEdicion(u)} aria-label={`Editar a ${u.nombre}`} title="Editar usuario"><Icon name="edit" size={17} /></button></div></div>) : <div className="usuarios-mensaje"><span><Icon name="users" size={25} /></span><strong>No hay usuarios para mostrar</strong><small>{usuarios.length ? 'Prueba con otros criterios de búsqueda.' : 'Crea el primer usuario del sistema.'}</small></div>}
    </div>
    <Paginacion />
    {crearAbierto && <div className="usuario-modal-fondo" onClick={cerrarFormulario}><form className="usuario-modal usuario-formulario" onSubmit={guardarUsuario} onClick={(e) => e.stopPropagation()}><button type="button" className="usuario-modal-cerrar" onClick={cerrarFormulario} aria-label="Cancelar y cerrar"><Icon name="close" /></button><div className="usuario-modal-titulo"><span><Icon name="users" size={23} /></span><div><h3>Crear nuevo usuario</h3><p>Registra sus datos personales y credenciales de acceso.</p></div></div>{errorFormulario && <div className="usuario-form-error">{errorFormulario}</div>}<div className="usuario-campos"><label>Nombre<input required value={formulario.nombre} onChange={(e) => setFormulario({ ...formulario, nombre: e.target.value })} placeholder="Ej. Gabriela" /></label><label>Apellido<input required value={formulario.apellido} onChange={(e) => setFormulario({ ...formulario, apellido: e.target.value })} placeholder="Ej. Vargas" /></label><label>Número de celular<input required type="tel" value={formulario.telefono} onChange={(e) => setFormulario({ ...formulario, telefono: e.target.value })} placeholder="Ej. 70000000" /></label><label>Correo electrónico<input required type="email" value={formulario.email} onChange={(e) => setFormulario({ ...formulario, email: e.target.value })} placeholder="nombre@correo.com" /><small>También podrá usarlo para iniciar sesión.</small></label><label>CI<input required value={formulario.ci} onChange={(e) => setFormulario({ ...formulario, ci: e.target.value })} placeholder="Número de identificación" /><small>También podrá usarlo para iniciar sesión.</small></label><label>Contraseña<input required type="password" autoComplete="new-password" value={formulario.password} onChange={(e) => setFormulario({ ...formulario, password: e.target.value })} placeholder="Mínimo 4 caracteres" /></label><label className="campo-confirmar">Confirmar contraseña<input required type="password" autoComplete="new-password" value={formulario.confirmarPassword} onChange={(e) => setFormulario({ ...formulario, confirmarPassword: e.target.value })} placeholder="Repite la contraseña" /></label></div><div className="usuario-form-acciones"><button type="button" onClick={cerrarFormulario}>Cancelar</button><button type="submit" className="usuarios-crear" disabled={guardando}><Icon name="check" size={17} />{guardando ? 'Guardando…' : 'Guardar usuario'}</button></div></form></div>}
    {viendoUsuario && <div className="usuario-modal-fondo" onClick={() => setViendoUsuario(null)}><div className="usuario-modal ficha-modal" onClick={(e) => e.stopPropagation()}><button className="usuario-modal-cerrar" onClick={() => setViendoUsuario(null)}><Icon name="close" /></button><div className="usuario-modal-titulo"><span><Icon name="users" size={23} /></span><div><h3>{viendoUsuario.nombre} {viendoUsuario.apellido}</h3><p>Información del usuario</p></div></div><div className="ficha-datos"><div><small>Correo</small><strong>{viendoUsuario.email}</strong></div><div><small>Celular</small><strong>{viendoUsuario.telefono || 'Sin registrar'}</strong></div><div><small>CI</small><strong>{viendoUsuario.ci || 'Sin registrar'}</strong></div><div><small>Rol</small><strong>{nombreRol(viendoUsuario.rolId)}</strong></div><div><small>Estado</small><strong>{viendoUsuario.estado}</strong></div><div><small>Registro</small><strong>{viendoUsuario.creadoEn ? new Date(viendoUsuario.creadoEn).toLocaleDateString('es-ES') : '—'}</strong></div></div><div className="usuario-form-acciones"><button onClick={() => setViendoUsuario(null)}>Cerrar</button><button className="usuarios-crear" onClick={() => { const u = viendoUsuario; setViendoUsuario(null); abrirEdicion(u); }}><Icon name="edit" size={16} />Editar usuario</button></div></div></div>}
    {editandoUsuario && <div className="usuario-modal-fondo" onClick={() => setEditandoUsuario(null)}><form className="usuario-modal usuario-formulario" onSubmit={guardarEdicion} onClick={(e) => e.stopPropagation()}><button type="button" className="usuario-modal-cerrar" onClick={() => setEditandoUsuario(null)}><Icon name="close" /></button><div className="usuario-modal-titulo"><span><Icon name="edit" size={22} /></span><div><h3>Editar usuario</h3><p>Actualiza sus datos y estado.</p></div></div>{errorFormulario && <div className="usuario-form-error">{errorFormulario}</div>}<div className="paciente-campos"><label>Nombre<input required value={edicion.nombre} onChange={(e) => setEdicion({ ...edicion, nombre: e.target.value })} /></label><label>Apellido<input required value={edicion.apellido} onChange={(e) => setEdicion({ ...edicion, apellido: e.target.value })} /></label><label>Celular<input required value={edicion.telefono} onChange={(e) => setEdicion({ ...edicion, telefono: e.target.value })} /></label><label>Correo<input required type="email" value={edicion.email} onChange={(e) => setEdicion({ ...edicion, email: e.target.value })} /></label><label>CI<input required value={edicion.ci} onChange={(e) => setEdicion({ ...edicion, ci: e.target.value })} /></label><label>Estado<select value={edicion.estado} onChange={(e) => setEdicion({ ...edicion, estado: e.target.value })}><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></label></div><div className="usuario-form-acciones"><button type="button" onClick={() => setEditandoUsuario(null)}>Cancelar</button><button className="usuarios-crear" disabled={guardando}><Icon name="check" size={16} />Guardar cambios</button></div></form></div>}
  </div>;
}
